config/routes.rb
Rails.application.routes.draw do
  get 'session/connect'

  get 'session/callback'

  get 'session/logout'

  get 'instagram/index'

  get 'instagram/feed'

  get 'instagram/tags'

  get 'instagram/tags_result'

  get 'instagram' => 'instagram/index'

  post 'instagram/tags'

  root :to => "instagram#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instagram_controller.rb
require "instagram"

class InstagramController < ApplicationController

  before_filter :auth, only: [:feed, :tags, :tags_result]
  before_filter :get_client,  only: [:feed, :tags, :tags_result]

  def auth
    redirect_to :controller => 'instagram' if !session[:access_token]
  end

  def index
    redirect_to :controller => 'instagram', :action => 'feed' if session[:access_token]
  end

  def feed
    @user = @client.user
    @recent_media_items = @client.user_recent_media
    @title = 'Home Page'
  end

  def tags
    if params[:q].present?
      @tags = @client.tag_search(params[:q])
    end
    @user = @client.user
    @title = 'HashTags'
  end

  def tags_result
    @tag_result = @client.tag_recent_media(params[:hashtag]) # Get the recent Instagram post or comment using hashtag
    @posts = @tag_result.paginate(:page => params[:page], :per_page => 10)
    @user = @client.user
  end

  private

  def get_client
    @client = Instagram.client(:access_token => session[:access_token])
  end
end

app/controllers/session_controller.rb
require "instagram"

class SessionController < ApplicationController
  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL, :scope => ['public_content','basic'])
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token
    redirect_to :controller => 'instagram', :action => 'feed'
  end

  def logout
    session.delete(:access_token)
    redirect_to :controller => 'instagram'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instagram_helper.rb
module InstagramHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/instagram/feed.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-3">
        <%= link_to image_tag('Instagram_icon.png', :class => 'icon'), instagram_feed_url %>
      </div>
      <div class="col-md-3 col-md-offset-6">
        <%= @user.username %>
        <%= image_tag(@user.profile_picture, :class => 'icon') %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= 'Hi ' + @user.full_name%>
    <hr>
    <div class="row">
      <ul class="captions">
        <% @recent_media_items.each do |media| %>
            <li>
              <%= image_tag (media.images.standard_resolution.url), :class => 'images' %>
            </li>
        <% end %>
      </ul>
    </div>
    <br>
    <hr>
    <%= link_to 'Search for hash tags here', :controller => 'instagram', :action => 'tags'%><br>
    <%= link_to 'Logout', :controller => 'session', :action => 'logout'%>
  </div>
</div>

app/views/instagram/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-3">
        <%= image_tag("Instagram_icon.png", :class => 'icon') %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <center>
    <%= button_to "Instagram Login", {:controller => :session, :action => :connect },
                  :class => "btn btn-primary", :method => :get, :style => "margin-top:30px" %>
    </center>
  </div>
</div>

app/views/instagram/tags.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-3">
        <%= image_tag('Instagram_icon.png', :class => 'icon') %>
      </div>
      <div class="col-md-3 col-md-offset-6">
        <%= @user.username %>
        <%= image_tag(@user.profile_picture, :class => 'icon') %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= 'Hi ' + @user.full_name%>
    <hr>

    <%= form_tag("/instagram/tags", method: "POST", class:"form-group") do %>
        <%= label_tag(:q, "Search for #Hashtags:") %>
        <%= text_field_tag(:q, @hashtag, :class => 'form-control', :required => 'required') %>
        <%= submit_tag("Search", :class => 'btn btn-primary', :style => 'margin-top: 10px') %>
    <% end %>

    <% if(@tags.present?) %>
      <table class="table table-condensed table-striped .table-bordered">
        <thead>
        <tr>
          <th>Hashtag</th>
          <th>Count</th>
          <th>Link</th>
        </tr>
        </thead>
        <tbody>
        <% @tags.each do |item| %>
        <tr>
          <td><%= '#'+item.name %></td>
          <td><%= item.media_count %></td>
          <td><%= link_to 'Link', :controller => 'instagram', :action => 'tags_result', :hashtag => item.name%><br></td>
        </tr>
        <% end%>
        </tbody>
      </table>
    <% elsif(!@tags.nil? && @tags.blank?) %>
        <p class="bg-danger text-danger">No results</p>
    <% end %>
    <hr>
    <%= link_to 'Back to Home Page', :controller => 'instagram', :action => 'feed'%><br>
    <%= link_to 'Logout', :controller => 'session', :action => 'logout'%>
  </div>
</div>

app/views/instagram/tags_result.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-3">
        <%= link_to image_tag('Instagram_icon.png', :class => 'icon'), instagram_feed_url %>
      </div>
      <div class="col-md-3 col-md-offset-6">
        <%= @user.username %>
        <%= image_tag(@user.profile_picture, :class => 'icon') %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <h4>Images for tag: #<%= params[:hashtag]%></h4>
    <hr>
    <div class="row">
      <ul class="captions">
        <% @posts.each do |media| %>
            <li>
              <%= image_tag (media.images.standard_resolution.url), :class => 'images' %>
            </li>
        <% end %>
      </ul>
    </div>
    <hr>
    <%= link_to 'Search for hash tags here', :controller => 'instagram', :action => 'tags'%><br>
    <%= link_to 'Logout', :controller => 'session', :action => 'logout'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= (@title.present?) ? (@title) : 'Instagram'%></title>
  <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-2.1.4.min', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'instagram.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/session/callback.html.erb
<h1>Session#callback</h1>
<p>Find me in app/views/session/callback.html.erb</p>

app/views/session/connect.html.erb
<h1>Session#connect</h1>
<p>Find me in app/views/session/connect.html.erb</p>